config/routes.rb
Rails.application.routes.draw do
  resources :taggings
  resources :tasks
  resources :tags
  match '/tasks/complete/:id' => 'tasks#complete', as: 'complete_task', via: :get
  root to: 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :tasks, through: :taggings

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :task
end

app/models/task.rb
class Task < ApplicationRecord
	validates :text, presence: true,
                    length: { minimum: 5 }
	has_many :taggings
	has_many :tags, through: :taggings
	
	def self.send_reminder
		@tasks = Task.all
		@tasks.each do|task|
			day = Time.now - Time.parse(task.title)
			# I send email to remind one hour before the task
			if  (((day / 3600).to_f >= -1) && ((day / 3600).to_f < 0)) 
				ExampleMailer.sample_email(task).deliver
			end
		end
	end
	
	def tag_list
		self.tags.collect do |tag|
			tag.name
		end.join(", ")
	end
	
	def tag_list=(tags_string)
	  tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
	  new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
	  self.tags = new_or_found_tags
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def index
		@q = Tag.ransack(params[:q])
		@tags = @q.result(distinct: true)
		@tags = @tags.sort { |a,b| a[:name] <=> b[:name] }
	end
 
	def show
	  @tag = Tag.find(params[:id])
	end
	
	def destroy
	  @tag = Tag.find(params[:id])
      @tag.destroy
      redirect_to tags_path
	end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController 
	def index
		@tasks = Task.all
		@tasks.each do|task|
			day = Time.now - Time.parse(task.title)
			# I send email to remind one hour before the task
			if  (((day / 3600).to_f >= -1) && ((day / 3600).to_f < 0)) 
				ExampleMailer.sample_email(task).deliver
			end
			task.title = Time.parse(task.title)
		end
		@tasks = @tasks.sort_by { |a| [a.completed ? 1 : 0, a.title] }
		respond_to do |format|
			format.html
			format.json
		end
	end

	def complete
		@task = Task.find(params[:id])
		@task.completed = true
		@task.save
	    redirect_to tasks_path
    end
	
	def show
		@task = Task.find(params[:id])
	end
 
	def edit
		@task = Task.find(params[:id])
	end
  
	def new
		@task = Task.new
		respond_to do |format|
			format.js { }
		end
	end
 
	def create
		@task = Task.new(task_params)

		respond_to do |format|		
			if @task.save
				flash[:success] = 'Task was successfully created.'
				format.html { redirect_to @task }
				format.json { render :show, status: :created, location: @task }
			else
				flash[:danger] = 'There was a problem creating the task.'
				format.html { render :new }
				format.json { render json: @task.errors, status: :unprocessable_entity }
			end
		end
	end
 
	def update
		@task = Task.find(params[:id])
		respond_to do |format|
			if @task.update(task_params)
				flash[:success] = 'Todo was successfully updated.'
				format.html { redirect_to @task}
				format.json { render :show, status: :ok, location: @task }
			else
				flash[:danger] = 'There was a problem updating the Todo.'
				format.html { render :edit }
				format.json { render json: @task.errors, status: :unprocessable_entity }
			end
		end
	end
 
	def destroy
		@task = Task.find(params[:id])
		@task.destroy 
		redirect_to tasks_path
	end

	private
	def task_params
		params.require(:task).permit(:title, :text, :tag_list)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cvwo</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <body>
     <%= render 'shared/navigation' %>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-12">
          <% flash.each do |name, msg| -%>
            <%= content_tag :div, msg, class: "alert alert-#{name}" %>
          <% end -%>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Hieu Todo</a>
    </div>
  </div>
</nav>

app/views/tags/index.html.erb
<h1>Listing Tags</h1>
<%= link_to "Main_page", controller: 'tasks' %>

<%= search_form_for @q do |f| %>
	<%= f.label :Tag %>
	<%= f.search_field :name_cont %>
	<%= f.submit %>
<% end %>

<table class = 'table'>
  <% @tags.each do |tag| %>
    <tr>
      <td class = 'active'><%= tag.name %></td>
      <td><%= link_to 'Show', tag_path(tag), class: 'btn btn-info btn-xs' %> | 
	  <%= link_to 'Destroy', tag_path(tag),
              method: :delete,
              data: { confirm: 'Are you sure?', class: 'btn btn-danger btn-xs'  } %> </td>
    </tr>
  <% end %>
</table>

app/views/tags/show.html.erb
<h1>Tasks Tagged with <%= @tag.name %></h1>
<%= link_to "Main_page", controller: 'tasks' %>
<ul>
  <% @tag.tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
 
	<% if @task.errors.any? %>
		<div id="error_explanation">
			<h2>
			<%= pluralize(@task.errors.count, "error") %> prohibited
			this article from being saved:
			</h2>
			<ul>
			<% @task.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>
<div class="field form-group">
    <%= f.label :time, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
</div>

<div class="field form-group">
    <%= f.label :action, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :text, class: 'form-control' %>
    </div>
</div>

<div class="field form-group">
    <%= f.label :tag_list, class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= f.text_area :tag_list, class: 'form-control' %>
    </div>
</div>

<div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit %>
	</div>
</div>
 
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<h1>Listing Tasks</h1>
<%= link_to new_task_path, remote: true do %>
    <button class="btn btn-default">New</button>
<% end %>
<%= link_to 'Tags list', controller: 'tags' %>
<div id="task-form" style="display:none;"></div>
<table class = 'table table-bordered'>
	<tr>
		<th>Status</th>
		<th>Time</th>
		<th>Action</th>
		<th colspan="3"></th>
	</tr>
 
	<% @tasks.each do |task| %>
		<tr>
			<% if task.completed == true %>
				<td class = 'active'> Completed </td>
			<% else %>
				<td class = 'active'> Not completed </td>
			<%end%> 
			<td>
				<span class="has-tooltip" data-toggle="tooltip" title="<%= "Created on #{task.created_at.strftime("%m/%e/%Y at %w:%M %p")}, Last modified on #{task.updated_at.strftime("%m/%e/%Y at %w:%M %p")}" %>">
				<%= task.title %>
				</span>
			</td>
			<td class = 'info'><%= task.text %>  </td> 
			<td><%= link_to 'Show', task_path(task), class: 'btn btn-primary btn-xs' %></td>
			<td><%= link_to 'Edit', edit_task_path(task), class: 'btn btn-info btn-xs'  %></td>
			<td><%= link_to 'Destroy', task_path(task),
				  method: :delete,
				  data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-xs' %></td>
	<% end %>
</table>

app/views/tasks/new.html.erb
<h1>New task</h1>
 
<% if @task.errors.any? %>
	<div id="error_explanation">
		<h2>
		<%= pluralize(@task.errors.count, "error") %> prohibited
		this article from being saved:
		</h2>
		<ul>
		<% @task.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>
 
<%= link_to 'Back', tasks_path %>

app/views/tasks/new.js.erb
$('#task-form').html("<%= j (render 'form') %>");
$('#task-form').slideDown(350);

app/views/tasks/show.html.erb
<p>
  <strong>Time:</strong>
  <%= @task.title %>
</p>
 
<p>
  <strong>Action:</strong>
  <%= @task.text %>
</p>

<p>
  Tags:
  <% @task.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<%= link_to 'Back', tasks_path, class: 'btn btn-default btn-xs' %> |
<%= link_to 'Mark', complete_task_path(@task), class: 'btn btn-primary btn-xs' %> |

app/views/welcome/index.html.erb
<h1>Hello Hieu!</h1>
<%= link_to 'My tasks', controller: 'tasks' %>